export default {
  business: '所属商家',
  name: '商品名称',
  category: '商品分类',
  brand: '品牌',
  type: '商品类型',
  tag: '商品标签',
  sellingPoint: '商品卖点',
  marketingType: '营销分类',
  afterSaleServiceTime: '售后服务时间',

  seoTitle: 'SEO标题',
  seoDescription: 'SEO描述',
  seoKeywords: 'SEO关键字',

  position: '适用位置',
  delivery: '可送货/安装',
  storage: '是否带储物空间',
  custom: '是否可订制',
  saleUnit: '单位',
  productionPlace: '产地',
  material: '材质',
  fabric: '面料',

  long: '长',
  wide: '宽',
  height: '高',
  cubage: '体积',
  weight: '重量',
  nationalDistribution: '是否支持全国配送',

  code: '物料编码',
  barCode: '条形码',
  moq: '起订量',
  supplyPrice: '供货价',
  maketPrice: '市场价',
  price: '售价',

  description: '介绍',
};
